#!/usr/bin/env bash
# Verify every external <img>/badge URL in README.md returns HTTP 200.
# Skips raw.githubusercontent.com/.../output/ URLs (the contribution-art branch is
# generated by a workflow and may not exist yet).
set -euo pipefail

README="${1:-README.md}"
fail=0

# Extract http(s) URLs from src="..." and markdown image ![](...).
urls=$(grep -oE 'https?://[^") ]+' "$README" | sort -u)

while IFS= read -r url; do
  [ -z "$url" ] && continue
  case "$url" in
    *raw.githubusercontent.com/*/output/*) echo "SKIP (generated): $url"; continue ;;
  esac
  code=$(curl -s -o /dev/null -L -w "%{http_code}" --max-time 20 "$url" || echo "000")
  if [ "$code" = "200" ]; then
    echo "OK   $code  $url"
  else
    echo "FAIL $code  $url"
    fail=1
  fi
done <<< "$urls"

exit "$fail"
